In [2]:
import matplotlib.image as mpimg
from matplotlib.image import imsave
import os
import matplotlib.image as mpimg
from skimage.io import imsave


In [3]:

# Output folder path for the cropped images
output_folder_path = "/mnt/DATA/dronetracking/Abhin/segement&detect/drone_detection_icpr_new/test/cropped"

# Directory containing the images
folder_path = '/mnt/DATA/dronetracking/Abhin/segement&detect/drone_detection_icpr_new/test/images'

# Directory containing the bounding box files
bbox_folder_path = '/mnt/DATA/dronetracking/Abhin/segement&detect/drone_detection_icpr_new/test/labels'

# Get a list of all image files in the directory
file_list = sorted([f for f in os.listdir(folder_path) if f.endswith('.png')])

# Loop through each image file and process the image with the corresponding bounding box
for idx, file_name in enumerate(file_list, start=1):
    image_path = os.path.join(folder_path, file_name)
    image = mpimg.imread(image_path)
    
    # Corresponding bounding box file path
    bbox_file_path = os.path.join(bbox_folder_path, f'{os.path.splitext(file_name)[0]}.txt')
    
    # Read the bounding box from the text file
    with open(bbox_file_path, 'r') as bbox_file:
        bbox = bbox_file.readline().strip()
    
    # Parse the bounding box coordinates
    dr_id, x, y, w, h = map(float, bbox.split())
    
    # Calculate the extended cropping coordinates
    y_min = int(y - (h / 4))
    y_max = int(y + h + (h / 4))
    x_min = int(x - (w / 4))
    x_max = int(x + w + (w / 4))
    
    # Ensure the coordinates are within the image bounds
    y_min = max(0, y_min)
    y_max = min(image.shape[0], y_max)
    x_min = max(0, x_min)
    x_max = min(image.shape[1], x_max)
    
    # Crop the image
    image_c = image[y_min:y_max, x_min:x_max]
    
    # Save the cropped image
    output_file_name = f'{idx:05d}_cropped.png'
    output_file_path = os.path.join(output_folder_path, output_file_name)
    imsave(output_file_path, image_c)
    print(image_c)


IndexError: cannot do a non-empty take from an empty axes.

In [4]:
image_path = "/mnt/DATA/dronetracking/Abhin/final_composition/paper_work_sample/LaSot/00000146.jpg"
image = mpimg.imread(image_path)


# Parse the bounding box coordinates
x, y, w, h = 653,363,105,53

# Calculate the extended cropping coordinates
y_min = int(y - (h / 4))
y_max = int(y + h + (h / 4))
x_min = int(x - (w / 4))
x_max = int(x + w + (w / 4))

# Ensure the coordinates are within the image bounds
y_min = max(0, y_min)
y_max = min(image.shape[0], y_max)
x_min = max(0, x_min)
x_max = min(image.shape[1], x_max)

# Crop the image
image_c = image[y_min:y_max, x_min:x_max]

# Save the cropped image
output_file_path = "/mnt/DATA/dronetracking/Abhin/final_composition/paper_work_sample/LaSot/146_cropped.png"
imsave(output_file_path, image_c)


[[[148 191 234]
  [148 191 234]
  [148 191 234]
  ...
  [154 199 240]
  [154 199 240]
  [154 199 240]]

 [[148 191 233]
  [148 191 233]
  [148 191 233]
  ...
  [154 199 240]
  [154 199 240]
  [154 199 240]]

 [[148 191 233]
  [148 191 233]
  [148 191 233]
  ...
  [154 199 240]
  [154 199 240]
  [154 199 240]]

 ...

 [[154 196 234]
  [154 196 234]
  [154 196 234]
  ...
  [160 199 228]
  [159 198 227]
  [160 199 228]]

 [[154 196 234]
  [154 196 234]
  [154 196 234]
  ...
  [162 201 230]
  [163 202 231]
  [164 203 232]]

 [[154 196 234]
  [154 196 234]
  [154 196 234]
  ...
  [165 202 229]
  [164 201 228]
  [163 200 227]]]


In [1]:
import os

# Define the directory path you want to enter
directory_path = "/mnt/DATA/dronetracking/segmentation/video1CropComp/U-2-Net/"

# Use the os.chdir() function to change the current working directory
os.chdir(directory_path)
current_directory = os.getcwd()
print("Current Directory:", current_directory)


Current Directory: /mnt/DATA/dronetracking/segmentation/video1CropComp/U-2-Net


In [2]:
!python /mnt/DATA/dronetracking/segmentation/video1CropComp/U-2-Net/u2net_test.py

['/mnt/DATA/dronetracking/Abhin/segement&detect/drone_detection_icpr_new/train/cropped/V_DRONE_0574_311.png']
...load U2NET---173.6 MB
Inferencing: V_DRONE_0574_311.png
/home/ee22m215/anaconda3/envs/segdrone/lib/python3.8/site-packages/torch/nn/functional.py:2796: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
/home/ee22m215/anaconda3/envs/segdrone/lib/python3.8/site-packages/torch/nn/functional.py:2970: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn("Default upsampling behavior when mode={} is changed "
/home/ee22m215/anaconda3/envs/segdrone/lib/python3.8/site-packages/torch/nn/functional.py:1569: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sig